# Generated by Django 5.2.7 on 2025-10-22 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('STRATEGIC', 'Strategic Affairs Office'), ('STATE_MINISTER', 'State Minister Office'), ('ADVISOR', 'State Minister Advisor Office')], max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='plans.unit')),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuarterlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('quarter', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('entry_window_start', models.DateTimeField(blank=True, null=True)),
                ('entry_window_end', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qreports_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qreports_created', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quarterly_reports', to='plans.unit')),
            ],
            options={
                'ordering': ['-year', '-quarter', 'unit__name'],
                'unique_together': {('year', 'quarter', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('owner_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='plans.unit')),
            ],
            options={
                'ordering': ['owner_unit__name', 'code'],
                'unique_together': {('owner_unit', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ANNUAL', 'Annual Plan'), ('QUARTERLY', 'Quarterly Report')], max_length=10)),
                ('file', models.FileField(upload_to='imports/')),
                ('year', models.PositiveIntegerField()),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('records_inserted', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports_uploaded', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports', to='plans.unit')),
            ],
        ),
        migrations.CreateModel(
            name='AnnualPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('entry_window_start', models.DateTimeField(blank=True, null=True)),
                ('entry_window_end', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans_created', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_plans', to='plans.unit')),
            ],
            options={
                'ordering': ['-year', 'unit__name'],
                'unique_together': {('year', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('STRATEGIC_AFFAIRS', 'Strategic Affairs'), ('STATE_MINISTER', 'State Minister'), ('ADVISOR', 'State Minister Advisor')], max_length=20)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='plans.unit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('SUBMIT', 'Submit'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('IMPORT', 'Import'), ('UPDATE', 'Update')], max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wf_actions', to=settings.AUTH_USER_MODEL)),
                ('context_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='plans.annualplan')),
                ('context_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='plans.quarterlyreport')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wf_logs', to='plans.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnualPlanTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('baseline_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='plans.annualplan')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_targets', to='plans.indicator')),
            ],
            options={
                'ordering': ['indicator__code'],
                'unique_together': {('plan', 'indicator')},
            },
        ),
        migrations.CreateModel(
            name='QuarterlyIndicatorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quarterly_entries', to='plans.indicator')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qentries_updated', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='plans.quarterlyreport')),
            ],
            options={
                'ordering': ['indicator__code'],
                'unique_together': {('report', 'indicator')},
            },
        ),
    ]
